In [17]:
import numpy as np
from scipy.ndimage.interpolation import shift

a = np.array([1,2,3,4,5,6])

In [20]:
a = a.reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a = np.array([shift(x,-1) for x in a])

In [29]:
shift([
       [[1,2,3],[4,5,6]],
       [[1,2,3],[4,5,6]]       
      ], [0, -1, 1]).reshape(2,6)

array([[0, 4, 5, 0, 0, 0],
       [0, 4, 5, 0, 0, 0]])

In [30]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a = np.array((1,2,3))
b = np.array((2,3,4))
c = np.vstack((a,b))
np.vstack((c,c,c))

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])